feat-(01-building-blocks): replaced failure with success in workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -9,9 +9,13 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:      
-      - name: Failed step
+      # - name: Failed step
+      #   run: |
+      #     echo "I will fail"      
+      #     exit 1
+      - name: Success step
         run: |
-          echo "I will fail"      
-          exit 1
+          echo "I will Succeed"
+          exit 0
       - name: Say Goodbye
         run: echo, Goodbye!
